version: '3.8'
name: salary-app-compose
services:
  #infrastructure
  salary-app-db:
    restart: always
    image: mysql:8.0
    container_name: salary-app-db
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: NewFakeSQL20
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: salary_app
    networks:
      default:
        ipv4_address: 172.23.0.3
  #services
  backend:
    restart: always
    container_name: salary-app-back
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: salary-app-db:3306
      DB_USER: root
      DB_PASS: NewFakeSQL20
    depends_on:
      - salary-app-db
    networks:
      default:
        ipv4_address: 172.23.0.2

  frontend:
    restart: always
    container_name: salary-app-front
    image: salary-app-front:latest
    ports:
      - 3000:80
    environment:
      API_BASE_URL: http://192.168.0.105:8080
    networks:
      default:
        ipv4_address: 172.23.0.5

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16